// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0T5aFWEJZCunnBiMtf1cFJlLDXogk41w',
    appId: '1:155995759757:web:8b7e09db6b7b70bed7eec4',
    messagingSenderId: '155995759757',
    projectId: 'medcar-20584',
    authDomain: 'medcar-20584.firebaseapp.com',
    storageBucket: 'medcar-20584.firebasestorage.app',
    measurementId: 'G-DDW5SGZ029',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3uCsZBJM3919FW4THC_fodc5pryxwLg',
    appId: '1:155995759757:android:bb660b23d667fa51d7eec4',
    messagingSenderId: '155995759757',
    projectId: 'medcar-20584',
    storageBucket: 'medcar-20584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6xqF9ugRfl0ARpgEULVx8cwLGkfqHFk',
    appId: '1:155995759757:ios:7ecc0d241ae598a8d7eec4',
    messagingSenderId: '155995759757',
    projectId: 'medcar-20584',
    storageBucket: 'medcar-20584.firebasestorage.app',
    iosBundleId: 'com.example.medcarFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6xqF9ugRfl0ARpgEULVx8cwLGkfqHFk',
    appId: '1:155995759757:ios:7ecc0d241ae598a8d7eec4',
    messagingSenderId: '155995759757',
    projectId: 'medcar-20584',
    storageBucket: 'medcar-20584.firebasestorage.app',
    iosBundleId: 'com.example.medcarFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0T5aFWEJZCunnBiMtf1cFJlLDXogk41w',
    appId: '1:155995759757:web:536c9b199b878f41d7eec4',
    messagingSenderId: '155995759757',
    projectId: 'medcar-20584',
    authDomain: 'medcar-20584.firebaseapp.com',
    storageBucket: 'medcar-20584.firebasestorage.app',
    measurementId: 'G-0TMFTWLLDR',
  );
}
